INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Воздушные шары', '100', 'static/img/product-2.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Торт на хэллуин', '500', 'static/img/product-3.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Маска зомби', '2570', 'static/img/product-4.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Маска Джека', '2570', 'static/img/product-5.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Искуственный череп', '900', 'static/img/product-6.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Костюм ведьмы', '7200', 'static/img/product-7.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Костюм вампира', '5680', 'static/img/product-8.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Венок на дверь', '1400', 'static/img/product-9.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Подвесная летучая мышь', '120', 'static/img/product-10.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Светящиеся приведения', '400', 'static/img/product-11.jpg')
INSERT INTO `goods` (`name`, `price`, `pic`) VALUES ('Свечи на хеллуин', '100', 'static/img/product-12.jpg')